syntax = "proto3";

package afs;

option go_package = "afsfs/generated/afs";


service AFSService {

  rpc Open       (OpenRequest)    returns (OpenResponse);
  rpc TestAuth   (TestAuthRequest)  returns (TestAuthResponse);
  rpc CreateFile (CreateFileRequest) returns (CreateFileResponse);
  rpc DeleteFile (DeleteFileRequest) returns (DeleteFileResponse);
  rpc CloseFile  (CloseFileRequest)  returns (CloseFileResponse);

  

  rpc FetchFile  (FetchFileRequest)       returns (stream FetchFileResponse);


  rpc StoreFile  (stream StoreFileRequest) returns (StoreFileResponse);



  rpc Replicate (stream ReplicateRequest) returns (ReplicateResponse);



  rpc Heartbeat       (HeartbeatRequest)       returns (HeartbeatResponse);
  rpc GetPrimary      (GetPrimaryRequest)       returns (GetPrimaryResponse);
  rpc AnnouncePrimary (AnnouncePrimaryRequest)  returns (AnnouncePrimaryResponse);



  rpc SyncState (SyncStateRequest) returns (stream SyncFileEntry);
}




message OpenRequest {
  string path      = 1;
  bool   write     = 2;
  string client_id = 3;
  int64  req_seq   = 4;
}

message OpenResponse {
  int64  file_handle_id = 1;
  string error          = 2;
}



message FetchFileRequest {
  string path = 1;
}

message FetchFileResponse {
  bytes  data    = 1;   
  int64  version = 2;   
  string error   = 3;   
}



message TestAuthRequest {
  string path           = 1;
  int64  cached_version = 2;
}

message TestAuthResponse {
  bool  is_valid = 1;
  int64 version  = 2;
}



message StoreFileRequest {
  string path      = 1;  
  bytes  data      = 2;  
  string client_id = 3;  
  int64  req_seq   = 4;  
}

message StoreFileResponse {
  int64  version = 1;
  string error   = 2;
}



message CreateFileRequest {
  string path      = 1;
  string client_id = 2;
  int64  req_seq   = 3;
}

message CreateFileResponse {
  int64  file_handle_id = 1;
  string error          = 2;
}



message DeleteFileRequest {
  string path      = 1;
  string client_id = 2;
  int64  req_seq   = 3;
}

message DeleteFileResponse {
  string error = 1;
}



message CloseFileRequest {
  int64 file_handle_id = 1;
}

message CloseFileResponse {
  string error = 1;
}



message ReplicateRequest {
  string operation = 1;  
  string path      = 2;  
  int64  version   = 3;  
  bytes  data      = 4;  
}

message ReplicateResponse {
  string error = 1;
}



message HeartbeatRequest {
  string server_id = 1;
}

message HeartbeatResponse {
  bool   is_primary = 1;
  string error      = 2;
}



message GetPrimaryRequest {}

message GetPrimaryResponse {
  string primary_addr = 1;
  string error        = 2;
}




message SyncStateRequest {
  string server_id = 1;
}

message SyncFileEntry {
  string path    = 1;  
  bytes  data    = 2;  
  int64  version = 3;  
}



message AnnouncePrimaryRequest {
  string primary_addr = 1;
  string primary_id   = 2;
}

message AnnouncePrimaryResponse {
  string error = 1;
}
